#!/usr/bin/env python
"""Generate -- and, when the workspaces exist, run -- the TRExFitter MultiFit of the three channels.

    python fit/run_multifit.py --dry-run      # write fit/comb.config and check it (no TRExFitter)
    python fit/run_multifit.py                # the above, then run the MultiFit

**The combination delivered in `result.md` is not this fit.** The channel workspaces
(`<channel>/fit/results/<job>/RooStats/*_model.root`) are not committed and were not rebuilt, so
the combination is done with the covariance method of `comb/` on the published per-channel
TRExFitter results. This script is the route to the joint profile-likelihood fit and is kept
ready: it is the natural next step and it is what `fitting/CONVENTIONS.md` section 5 prescribes.

To get there, from the repository root:

    git submodule update --init --recursive
    bash fitting/build_trexfitter.sh
    source setup.sh
    cd z-mumu   && python run_v2.py --from 4        # ~40 min: histograms -> fit inputs -> h/w/f
    cd ../z-tautau && python run_all.py --from 3    # ~25 min: fake factors, BDT, histograms -> h/w/f
    cd ../z-ee && trex-fitter hwf fit.config        # after it adopts CONVENTIONS sections 1-3
    cd ../combination && python fit/run_multifit.py

What the joint fit adds over the covariance combination (see docs/03-method.md):

* the shared nuisance parameters are *profiled* together, so the mu mu channel's data can
  constrain `Lumi`, `Pileup`, `L1Prefiring` and the theory parameters for the tau tau channel too;
* the tau tau channel's asymmetric likelihood is used exactly rather than through a bifurcated
  Gaussian approximation;
* per-bin MC-statistics gammas stay per-bin instead of being collapsed into one `Gammas` category.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
sys.path.insert(0, str(REPO))

from fitting import trexconfig as tc  # noqa: E402

CONFIG = HERE / "comb.config"

#: the channels entering the combination.
#: z-ee's config is the job it published (`z-ee/fit.config`, job name `Zee_fit`); its POI is still
#: `mu_signal` and its region/sample names are its own, so the MultiFit below cannot be run
#: against it until the channel adopts `fitting/CONVENTIONS.md` sections 1-3 -- see
#: `zee_conventions_problems()` and combination/docs/01-inputs.md.
CHANNELS = [
    {"job": "zmumu", "config": "../../z-mumu/fit/zmumu.config",
     "directory": "../../z-mumu/fit/results/zmumu", "label": "#mu#mu"},
    {"job": "ztautau", "config": "../../z-tautau/fit/ztautau.config",
     "directory": "../../z-tautau/fit/results/ztautau", "label": "#tau_{h}#tau_{h}"},
    {"job": "Zee_fit", "config": "../../z-ee/fit.config",
     "directory": "../../z-ee/fit/results/Zee_fit", "label": "ee"},
]

#: what z-ee has to change before the MultiFit can actually be run over its workspace.
#: Checked against the committed config by `zee_conventions_problems()`; reported, not enforced.
ZEE_REQUIREMENTS = [
    ("POI: mu_Z", "POI: mu_signal", "the MultiFit fits one POI by name; `mu_Z` in every channel"),
    ("Region: ee_SR", "Region: \"SR\"",
     "region names must be globally unique -- MultiFit warns and does not merge them"),
    ("Sample: DYee ... Type: SIGNAL", "Sample: \"DY_ee\" ... Type: BACKGROUND",
     "the signal must be typed SIGNAL, and named per section 1"),
    ("Systematic names Lumi / ElectronID / ElectronReco / XS_*",
     "LUMI / ElectronID / ElectronRECO / XS_VV",
     "nuisance parameters are correlated by *name*: `LUMI` != `Lumi`, `XS_VV` != `XS_WW`+`XS_WZ`+`XS_ZZ`"),
    ("PDF / QCDScale renormalised to a constant yield", "raw LHE weight envelopes",
     "section 3. Un-renormalised, `QCDScale` is a +-5.9 % normalisation degenerate with the POI, "
     "and in a joint fit it would be one parameter shared with two channels that do it correctly"),
]

#: MultiFit block keys of TRExFitter v1.8.0 that this config uses, for the offline syntax check.
MULTIFIT_KEYS = {
    "Label", "OutputDir", "Combine", "Compare", "ComparePOI", "ComparePulls", "CompareLimits",
    "PlotCombCorrMatrix", "POIName", "POIRange", "POIPrecision", "DataName", "CmeLabel",
    "LumiLabel", "NumCPU", "FitType", "SetRandomInitialNPval", "ShowObserved", "LimitTitle",
    "POITitle", "SaveSuf", "ComparePOIPlotTitle", "UseRnd", "ConfigFile", "Directory", "Label",
    "Options",
}
FIT_KEYS = {"ConfigFile", "Directory", "Label", "Options", "LoadSuf"}

HEADER = """Combination of the three Z -> ll channels measured on CMS Open Data 2016 (G+H).
Generated by combination/fit/run_multifit.py -- do not edit by hand.

TRExFitter v1.8.0 MultiFit over the individual channel workspaces (fitting/CONVENTIONS.md, 5).
Run from combination/fit/ once every channel has produced its workspace with `trex-fitter h w`:

    trex-fitter mwf comb.config      combined workspace + fit
    trex-fitter mdp comb.config      pre-/post-fit plots and the POI comparison
    trex-fitter mr  comb.config      ranking of the combined fit
    trex-fitter mi  comb.config      grouped impacts, same Category strings as the channels

Stat-only: run every channel and this file with  "StatOnly=TRUE:Suffix=_statOnly".

Correlation model: nuisance parameters are correlated by *name*, so everything the channels named
identically (Lumi, Pileup, L1Prefiring, XS_*, PDF, QCDScale, PS_ISR, PS_FSR) is one parameter in
the combined likelihood. That is what the shared conventions were written for.

`SigModel` needs no action as the three channels stand today: only z-mumu fits it (powheg vs
aMC@NLO, both NLO, two-sided inside a common 50 < m_LHE < 120 GeV window). z-tautau dropped its
own generator systematic in v2.1 -- `SigModel_tautau` (madgraph LO vs aMC@NLO) is reported and not
fitted, and it is not in the workspace (z-tautau/docs/07, docs/08); z-ee has none. If a channel switches
it on (`config.SIGMODEL_IN_FIT = True`), the two must be decorrelated, because an LO-vs-NLO
difference and an NLO-vs-NLO difference are not one nuisance parameter -- add to each channel's
Job block, before building the workspace:

    DecorrSysts: "SigModel"
    DecorrSuff: "_mumu"        (resp. "_tautau")

A second caveat with no effect at this precision: Z/gamma* -> tautau is a *background* in the
mu mu signal region (11.0k of 10.4M events) carrying an independent 5 % XS_DYtautau nuisance,
while it is the signal of the tautau channel. Under lepton universality it should scale with mu_Z;
the difference is 0.005 % on the combined result. The same holds for Z -> tautau in the ee signal
region (6.7k of 6.32M events).

z-ee is listed as a Fit block but its committed config does not yet follow sections 1-3 of the
conventions (POI `mu_signal`, region `SR`, sample `DY_ee` typed BACKGROUND, `LUMI` instead of
`Lumi`, and un-renormalised PDF/QCDScale templates). Running the MultiFit against it as it stands
would produce a joint fit with two unrelated POIs and uncorrelated luminosity. `python
fit/run_multifit.py --dry-run` prints the list."""


def build_config() -> str:
    blocks = [tc.block("MultiFit", "comb",
                       Label="Z #rightarrow ll combination (#mu#mu + #tau_{h}#tau_{h} + ee)",
                       OutputDir="results", Combine=True, Compare=True, ComparePOI=True,
                       ComparePulls=True, PlotCombCorrMatrix=True, POIName="mu_Z",
                       POIRange="0.8:1.4", POIPrecision=3, DataName="obsData",
                       CmeLabel="13 TeV", LumiLabel="16.4 fb^{-1}", NumCPU=4)]
    for ch in CHANNELS:
        blocks.append(tc.block("Fit", ch["job"], ConfigFile=ch["config"],
                               Directory=ch["directory"], Label=ch["label"]))
    return tc.render(blocks, header=HEADER)


def check_config(text: str) -> list[str]:
    """Offline syntax check: block structure and key names, without running TRExFitter."""
    problems, kind = [], None
    seen_blocks = []
    for n, raw in enumerate(text.splitlines(), 1):
        line = raw.split("%")[0].rstrip() if raw.lstrip().startswith("%") else raw.rstrip()
        if not line.strip() or raw.lstrip().startswith("%"):
            continue
        if not line.startswith(" "):
            if ":" not in line:
                problems.append(f"line {n}: block line without ':' -- {line!r}")
                continue
            kind = line.split(":", 1)[0].strip()
            seen_blocks.append(kind)
            if kind not in ("MultiFit", "Fit"):
                problems.append(f"line {n}: unexpected block {kind!r} in a MultiFit config")
            continue
        if ":" not in line:
            problems.append(f"line {n}: option without ':' -- {line!r}")
            continue
        key = line.split(":", 1)[0].strip()
        allowed = MULTIFIT_KEYS if kind == "MultiFit" else FIT_KEYS
        if key not in allowed:
            problems.append(f"line {n}: {key!r} is not a {kind} option of TRExFitter v1.8.0")
    if seen_blocks[:1] != ["MultiFit"]:
        problems.append("the MultiFit block must come first")
    if seen_blocks.count("Fit") < 2:
        problems.append("a combination needs at least two Fit blocks")
    return problems


def zee_conventions_problems() -> list[str]:
    """Report which of `ZEE_REQUIREMENTS` the committed z-ee config still violates."""
    cfg = (HERE / "../../z-ee/fit.config").resolve()
    if not cfg.exists():
        return [f"z-ee config not found: {cfg}"]
    text = cfg.read_text()
    out = []
    for want, have, why in ZEE_REQUIREMENTS:
        key = want.split(":")[0].split(" ")[0]
        if key == "POI" and "POI: mu_Z" in text:
            continue
        if key == "Region" and "ee_SR" in text:
            continue
        if key == "Sample" and 'Sample: "DYee"' in text:
            continue
        if key == "Systematic" and "Systematic: \"Lumi\"" in text:
            continue
        if key == "PDF":
            continue        # cannot be seen in the config; it is a property of the histograms
        out.append(f"{want}   (has: {have})\n      -> {why}")
    return out


def missing_workspaces() -> list[str]:
    out = []
    for ch in CHANNELS:
        ws = (HERE / ch["directory"] / "RooStats" / f"{ch['job']}_combined_{ch['job']}_model.root").resolve()
        cfg = (HERE / ch["config"]).resolve()
        if not cfg.exists():
            out.append(f"config missing: {cfg}")
        if not ws.exists():
            out.append(f"workspace missing: {ws}")
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--dry-run", action="store_true", help="write and check the config, do not run")
    ap.add_argument("--actions", default="mwf,mdp,mr,mi", help="comma-separated trex-fitter actions")
    args = ap.parse_args()

    text = build_config()
    CONFIG.write_text(text)
    print(f"wrote {CONFIG.relative_to(REPO)} ({len(text.splitlines())} lines)")

    problems = check_config(text)
    if problems:
        print("config check FAILED:")
        print("\n".join("  " + p for p in problems))
        sys.exit(1)
    print("config check: pass (block structure and MultiFit/Fit option names)")

    problems = zee_conventions_problems()
    if problems:
        print("\nz-ee does not yet follow fitting/CONVENTIONS.md sections 1-3, so the MultiFit\n"
              "cannot be run against its workspace even once that workspace exists:")
        print("\n".join("  * " + p for p in problems))
        print("  * PDF / QCDScale renormalised to a constant yield   (has: raw LHE weight "
              "envelopes)\n      -> section 3; see combination/docs/01-inputs.md")

    missing = missing_workspaces()
    if missing:
        print("\nthe MultiFit cannot run yet -- rebuild the channel workspaces first:")
        print("\n".join("  " + m for m in missing))
        print("\n" + __doc__.split("To get there, from the repository root:")[1].split("What the joint fit adds")[0].rstrip())
        sys.exit(0 if args.dry_run else 2)
    if args.dry_run:
        print("\nworkspaces are present; rerun without --dry-run to fit")
        return

    exe = shutil.which("trex-fitter")
    if exe is None:
        sys.exit("trex-fitter not on PATH: source ../setup.sh and run fitting/build_trexfitter.sh")
    for action in args.actions.split(","):
        print(f"\n=== trex-fitter {action} comb.config")
        subprocess.run([exe, action, CONFIG.name], cwd=HERE, check=True)


if __name__ == "__main__":
    main()
