#!/usr/bin/env python
"""TRExFitter MultiFit of Z -> ee, Z -> mumu and Z -> tau_h tau_h (CMS Open Data 2016 G+H).

    source ../../setup.sh
    python run.py all          # everything below, in order

    python run.py prepare      # ee inputs from z-ee/Zee_fit.tar.gz; channel and MultiFit configs in work/
    python run.py workspaces   # trex-fitter hw for every channel config
    python run.py fits         # combined fit (with likelihood scan), three-POI fit, standalone channel fits, stat-only fit
    python run.py variations   # the alternative likelihoods of config/channels.json "variations"
    python run.py impacts      # NP ranking of the combined fit (one refit job per parameter, parallel)
    python run.py results      # -> output/result.json
    python run.py plots        # -> output/plots/

Likelihoods (work/<name>/):
    common     one POI mu_Z for all channels: the combined cross section sigma = mu_Z x poi.reference_pb
    split      mu_Z_ee, mu_Z_mumu, mu_Z_tautau with all shared nuisance parameters profiled together:
               per-channel cross sections and the compatibility test -2 ln(L_common / L_split)
    var_<name> one per entry of "variations", common POI
TRExFitter output goes to work/ (git-ignored); what is kept is output/.
"""

from __future__ import annotations

import argparse
import copy
import json
import re
import subprocess
import time

from mf import ee_input, trexcfg
from mf.paths import WORK, manifest, repo_path

from fitting import run_trex  # noqa: E402  (mf.paths puts the repository root on sys.path)


def fit_options(m):
    return {k: v for k, v in m.get("fit", {}).items() if not k.startswith("_")}


def likelihoods(m):
    """{name: {"model": common|split, "channels": {key: spec}}} for every likelihood this folder fits."""
    out = {"common": {"model": "common", "channels": m["channels"]},
           "split": {"model": "split", "channels": m["channels"]}}
    for name, var in m.get("variations", {}).items():
        if name.startswith("_"):
            continue
        chans = {k: copy.deepcopy(v) for k, v in m["channels"].items() if k in var.get("channels", m["channels"])}
        for k, split in var.get("split", {}).items():
            chans[k]["split_shape_norm"] = split
        for k, over in var.get("overall", {}).items():
            chans[k]["overall"] = over
        out[f"var_{name}"] = {"model": "common", "channels": chans, "label": var["label"]}
    return out


def prepare(args):
    m = manifest()
    poi = m["poi"]
    status = {"ee_input": ee_input.extract(m["channels"]["ee"]["inputs"], WORK / "inputs" / "ee"), "likelihoods": {}}
    if abs(status["ee_input"]["sigma_reference_pb"] - m["channels"]["ee"]["sigma_reference_pb"]) > 1e-6:
        raise ValueError("config/channels.json: ee sigma_reference_pb differs from the tarball's reference_cross_section.txt")
    for name, lk in likelihoods(m).items():
        wdir = WORK / name
        wdir.mkdir(parents=True, exist_ok=True)
        fits, pois, info = [], [], {}
        for key, spec in lk["channels"].items():
            pname = poi["name"] if lk["model"] == "common" else f'{poi["name"]}_{key}'
            histo_path = WORK / "inputs" / "ee" if key == "ee" else repo_path(spec["histo_path"])
            blocks, info[key] = trexcfg.adapt_channel(key, spec, poi, pname, wdir, histo_path, fit_options(m))
            cfg = wdir / f"{key}.config"
            cfg.write_text(trexcfg.render(blocks, header=f"Generated by combination/combLieke/run.py prepare from {spec['config']}\n"
                                                         f"(likelihood '{name}'). Edit config/channels.json or mf/trexcfg.py, not this file."))
            fits.append({"job": key, "config": str(cfg), "directory": str(wdir / key), "label": spec["label"]})
            pois.append(pname)
        mpois = pois if lk["model"] == "split" else [poi["name"]]
        (wdir / "multifit.config").write_text(trexcfg.render(
            trexcfg.multifit("combination", fits, mpois, wdir, {**poi, "fit": fit_options(m)}, scan=(name == "common")),
            header=f"Generated by combination/combLieke/run.py prepare (likelihood '{name}')."))
        if name == "common":   # the stat-only fit must not overwrite the likelihood scan of the full fit
            (wdir / "multifit_statonly.config").write_text(trexcfg.render(
                trexcfg.multifit("combination", fits, mpois, wdir, {**poi, "fit": fit_options(m)}, scan=False),
                header="Generated by combination/combLieke/run.py prepare: the common likelihood without the scan, for the stat-only fit."))
        status["likelihoods"][name] = {"model": lk["model"], "pois": mpois, "channels": info, "label": lk.get("label", name)}
    (WORK / "status.json").write_text(json.dumps(status, indent=1) + "\n")
    print(f"prepared {len(status['likelihoods'])} likelihoods in {WORK}; ee inputs: {status['ee_input']['histograms']} histograms, "
          f"max. relative difference to {status['ee_input'].get('check_against')}: {status['ee_input'].get('max_relative_difference')}")


STAT_ONLY = "StatOnly=TRUE:Suffix=_statOnly"


def trex(config, actions, log, options=None):
    """trex-fitter <actions> <config> [<options>]; full output to `log`, the fit summary lines echoed."""
    t0 = time.time()
    print(f"trex-fitter {actions} {config.relative_to(WORK)}" + (f" {options}" if options else ""), flush=True)
    log.parent.mkdir(parents=True, exist_ok=True)
    with open(log, "w") as fh:
        code = subprocess.run([run_trex.trex_binary(), actions, str(config)] + ([options] if options else []),
                              cwd=config.parent, stdout=fh, stderr=subprocess.STDOUT).returncode
    keep = re.compile(r"minuit status|hess status|minos status|Edm =|probability =|Fit failure")
    summary = [re.sub(r"\x1b\[[0-9;]*m", "", line).split("|", 1)[-1].strip()
               for line in log.read_text(errors="replace").splitlines() if keep.search(line)]
    print("   " + "; ".join(summary[-5:]) + f"  [exit {code}, {time.time() - t0:.0f} s]", flush=True)
    if code != 0:
        raise RuntimeError(f"trex-fitter {actions} {config} failed (exit {code}); see {log}")


def _names(args, prefix=None):
    names = list(likelihoods(manifest()))
    if prefix is not None:
        names = [n for n in names if n.startswith(prefix)]
    return [n for n in names if not args.only or n in args.only]


def workspaces(args):
    for name in _names(args):
        for cfg in sorted((WORK / name).glob("*.config")):
            if not cfg.name.startswith("multifit"):
                trex(cfg, "hw", WORK / name / "logs" / f"{cfg.stem}_hw.log")


def fits(args):
    m = manifest()
    for name in [n for n in ("common", "split") if not args.only or n in args.only]:
        trex(WORK / name / "multifit.config", "mwf", WORK / name / "logs" / "multifit_mwf.log")
    if not args.only or "common" in args.only:
        for key in m["channels"]:
            trex(WORK / "common" / f"{key}.config", "f", WORK / "common" / "logs" / f"{key}_f.log")
        # data-statistics-only uncertainty: every channel workspace and the combination without NPs or gammas
        for key in m["channels"]:
            trex(WORK / "common" / f"{key}.config", "hw", WORK / "common" / "logs" / f"{key}_hw_statOnly.log", STAT_ONLY)
        trex(WORK / "common" / "multifit_statonly.config", "mwf", WORK / "common" / "logs" / "multifit_mwf_statOnly.log", STAT_ONLY)


def variations(args):
    for name in _names(args, "var_"):
        trex(WORK / name / "multifit.config", "mwf", WORK / name / "logs" / "multifit_mwf.log")


def impacts(args):
    """Refit-based ranking of every nuisance parameter except the MC-statistics gammas, one
    `trex-fitter mr ... Ranking=<NP>` per parameter in parallel, merged into Fits/NPRanking_mu_Z.txt.

    TRExFitter selects NPs by substring (Ranking=PDF also refits Acc_PDF and PDF_eeShape); the merge
    keeps each parameter's own row. The uncertainty groups come from the covariance decomposition that
    mwf writes: TRExFitter's refit-based grouped impacts (`mi`) fail HESSE in this likelihood (README)."""
    from concurrent.futures import ThreadPoolExecutor
    wdir, poi = WORK / "common", manifest()["poi"]["name"]
    fits_dir = wdir / "combination" / "Fits"
    names = [n for n in run_trex.parse_fit_txt(fits_dir / "combination.txt")["nps"] if not n.startswith(("gamma", poi))]
    for old in fits_dir.glob("NPRanking*"):
        old.unlink()
    t0 = time.time()

    def one(name):
        with open(wdir / "logs" / f"rank_{name}.log", "w") as fh:
            return name, subprocess.run([run_trex.trex_binary(), "mr", str(wdir / "multifit.config"), f"Ranking={name}"],
                                        cwd=wdir, stdout=fh, stderr=subprocess.STDOUT).returncode

    with ThreadPoolExecutor(max_workers=args.workers) as pool:
        codes = dict(pool.map(one, names))
    failed = [n for n, c in codes.items() if c != 0]
    rows = {}
    for n in names:
        path = fits_dir / f"NPRanking_{n}_{poi}.txt"
        for line in (path.read_text().splitlines() if path.exists() else []):
            if line.split() and line.split()[0] == n:
                rows[n] = line
    missing = [n for n in names if n not in rows]
    (fits_dir / f"NPRanking_{poi}.txt").write_text("\n".join(rows[n] for n in names if n in rows) + "\n")
    print(f"ranking: {len(rows)}/{len(names)} parameters in {time.time() - t0:.0f} s"
          + (f"; failed: {failed}" if failed else "") + (f"; missing: {missing}" if missing else ""), flush=True)


def results(args):
    from mf import results as res
    res.collect()


def plots(args):
    from mf import plots as pl
    pl.make_all()


STEPS = {"prepare": prepare, "workspaces": workspaces, "fits": fits, "variations": variations,
         "impacts": impacts, "results": results, "plots": plots}


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("step", choices=list(STEPS) + ["all"])
    ap.add_argument("--only", nargs="*", default=None, help="restrict workspaces/fits/variations to these likelihoods")
    ap.add_argument("--workers", type=int, default=6, help="parallel trex-fitter processes for the ranking")
    args = ap.parse_args()
    for step in (STEPS if args.step == "all" else [args.step]):
        STEPS[step](args)


if __name__ == "__main__":
    main()
