executable = /project/atlas/users/sjankovy/BND/BND-school/z-tautau/condor/run_step5.sh
arguments  = $(args)

output = /project/atlas/users/sjankovy/BND/BND-school/z-tautau/condor/out/step5_$(Cluster).$(Process).log
error  = /project/atlas/users/sjankovy/BND/BND-school/z-tautau/condor/err/step5_$(Cluster).$(Process).log
log    = /project/atlas/users/sjankovy/BND/BND-school/z-tautau/condor/logs/step5_$(Cluster).log

stream_output = True
stream_error  = True

accounting_group = atlas

request_cpus   = 4
request_memory = 6GB

+JobCategory = "short"
+SingularityImage    = "/cvmfs/atlas.cern.ch/repo/containers/fs/singularity/x86_64-almalinux9"
+SingularityBindCVMFS = True

JobBatchName = "ztt_fit"

queue args from /project/atlas/users/sjankovy/BND/BND-school/z-tautau/condor/params_step5.txt
