#!/usr/bin/env python
"""Step 5b -- the TRExFitter MultiFit of the four per-channel workspaces (docs/11-combination-inputs.md).

    python scripts/step5b_multifit.py [--channels tautau mutau etau emu] [--actions mwf]

Writes fit/comb.config (committed) and runs `trex-fitter mwf comb.config` from fit/. Each Fit block points
at one channel's own config and results directory (step 5 with --channels <ch> --job ztautau_<ch>), whose
fit inputs are the per-channel export of step 4b. Nuisance parameters are correlated by *name* across the
workspaces, so this MultiFit is the same model as the single-file fit -- which is exactly the check the
combination needs before it adds the z-mumu and z-ee workspaces as further Fit blocks.

The result goes to fit/results/comb_fit_result.json; step 6 quotes it next to the single-file fit.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from fitting import run_trex  # noqa: E402
from ztautau import config  # noqa: E402

sys.path.insert(0, str(Path(__file__).resolve().parent))
from step5_fit import trex_environment  # noqa: E402

LABELS = {"tautau": "#tau_{h}#tau_{h}", "mutau": "#mu#tau_{h}", "etau": "e#tau_{h}", "emu": "e#mu"}
HEADER = """% Combination of the four Z -> tautau channels as a TRExFitter v1.8.0 MultiFit over the per-channel
% workspaces (docs/CONVENTIONS.md section 5, z-tautau/docs/11-combination-inputs.md). Each channel job
% reads its own exported fit inputs (fit/fitinputs/ztautau_<channel>.root, scripts/step4b_export_channels.py)
% with the tau_h ID scale factors free; shared nuisance-parameter names (TauIDSF_DM*, TauES_DM*, Lumi,
% Pileup, ...) are correlated by name, so this MultiFit is the same model as the single-file fit of step 5.
% Generated by scripts/step5b_multifit.py -- do not edit by hand. Run from fit/:
%     trex-fitter mwf comb.config      trex-fitter mdp comb.config
%     trex-fitter mr  comb.config      trex-fitter mi  comb.config
% To add the other groups' channels append Fit blocks pointing at ../../z-mumu/fit/zmumu.config etc.;
% z-mumu's ttbar control region mumu_CRemu shares events with our emu_SR and must be dropped there, and
% every channel must keep its own sigma^pred(60-120) (docs/11-combination-inputs.md).
"""


def build_config(channels, job="comb") -> str:
    lines = [HEADER, f'MultiFit: "{job}"', '  Label: "Z #rightarrow #tau#tau, four channels"',
             '  OutputDir: "results"', "  Combine: TRUE", "  Compare: TRUE", "  ComparePOI: TRUE",
             "  ComparePulls: TRUE", "  PlotCombCorrMatrix: TRUE", '  POIName: "mu_Z"', "  POIRange: 0.8:1.3",
             '  DataName: "obsData"', '  CmeLabel: "13 TeV"', '  LumiLabel: "16.4 fb^{-1}"', "  NumCPU: 6", ""]
    for ch in channels:
        j = f"{config.JOB_V4}_{ch}"
        lines += [f'Fit: "{j}"', f"  ConfigFile: {j}.config", f"  Directory: results/{j}",
                  f'  Label: "{LABELS.get(ch, ch)}"', ""]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--channels", nargs="*", default=config.CHANNELS)
    ap.add_argument("--actions", default="mwf")
    ap.add_argument("--config-only", action="store_true")
    ap.add_argument("--job", default="comb")
    args = ap.parse_args()
    fitdir = config.FIT_DIR_V4
    cfg = fitdir / f"{args.job}.config"
    cfg.write_text(build_config(args.channels, args.job))
    print(f"config -> {cfg} ({len(args.channels)} channel workspaces)")
    missing = [ch for ch in args.channels
               if not (fitdir / "results" / f"{config.JOB_V4}_{ch}" / "RooStats").exists()]
    if missing:
        raise SystemExit(f"no workspace for {missing}: run step 5 with --channels <ch> --job {config.JOB_V4}_<ch> first")
    if args.config_only:
        return
    trex_environment()
    run_trex.run(cfg.name, args.actions, cwd=fitdir, log=f"results/{args.job}/logs/{args.actions}.log")
    fits = fitdir / "results" / args.job / "Fits"
    res = {"job": args.job, "poi": "mu_Z", "channels": args.channels,
           "note": "TRExFitter MultiFit of the per-channel workspaces; the same model as the single-file fit"}
    txt = fits / f"{args.job}.txt"
    if txt.exists():
        parsed = run_trex.parse_fit_txt(txt)
        v = parsed["nps"].get("mu_Z")
        if v:
            res.update(poi_value=v[0], poi_err_up=v[1], poi_err_down=v[2], poi_err=0.5 * (v[1] + v[2]))
        res["nps"] = {k: val for k, val in parsed["nps"].items() if k != "mu_Z"}
        res["nll"] = parsed["nll"]
    for name, key in ((f"{args.job}_errDecomp_mu_Z.txt", "err_decomp"), (f"{args.job}_group_errDecomp_mu_Z.txt", "grouped_impact")):
        if (fits / name).exists():
            parser = run_trex.parse_err_decomp if key == "err_decomp" else run_trex.parse_grouped
            res[key] = {k: v[0] for k, v in parser(fits / name).items()}
    out = fitdir / "results" / f"{args.job}_fit_result.json"
    out.write_text(json.dumps(res, indent=1, default=float))
    print(f"MultiFit mu_Z = {res.get('poi_value')} +{res.get('poi_err_up')} -{res.get('poi_err_down')} -> {out}")


if __name__ == "__main__":
    main()
