// Class include
#include "TRExFitter/Systematic.h"

// -------------------------------------------------------------------------------------------------
// Systematic

//_____________________________________________________________________________
//
Systematic::Systematic(const std::string& name,int type,double up,double down) :
    fName(name),
    fNuisanceParameter(name),
    fTitle(name),
    fCategory(""),
    fSubCategory("Uncategorised"),
    fStoredName(name),
    fType(type),
    fSmoothType(0),
    fPreSmoothing(false),
    fSampleSmoothing(false),
    fSampleSmoothOption(HistoTools::MAXVARIATION),
    fSymmetrisationType(HistoTools::NOSYMMETRIZATION),
    fReferenceSample(""),
    fReferenceSmoothing(""),
    fReferencePruning(""),
    fOverallUp(up),
    fOverallDown(down),
    fScaleUp(1.),
    fScaleDown(1.),
    fHasUpVariation(true),
    fHasDownVariation(true),
    fIsFreeParameter(false),
    fIsCorrelated(true),
    fIsShapeAccDecorr(false),
    fIsRegionDecorr(false),
    fIsSampleDecorr(false),
    fIsShapeOnly(false),
    fIsNormOnly(false),
    fNoPruning(false),
    fWeightUp(""),
    fWeightSufUp(""),
    fNtuplePathSufUp(""),
    fFriendPathSufUp(""),
    fNtupleFileSufUp(""),
    fNtupleNameSufUp(""),
    fWeightDown(""),
    fWeightSufDown(""),
    fNtuplePathSufDown(""),
    fNtupleFileSufDown(""),
    fNtupleNameSufDown(""),
    fFriendPathSufDown(""),
    fIgnoreWeight(""),
    fHistoPathSufUp(""),
    fHistoFileSufUp(""),
    fHistoNameSufUp(""),
    fHistoPathSufDown(""),
    fHistoFileSufDown(""),
    fHistoNameSufDown(""),
    fSampleUp(""),
    fSampleDown(""),
    fCombineType(Systematic::COMBINATIONTYPE::STANDARDDEVIATION),
    fForceShape(HistoTools::FORCESHAPETYPE::NOSHAPE) {
}
