"""Render `result.md` from the combination payload, so the prose can never drift from the numbers.

`run_combination.py` calls `write_result_md`; every figure in the file comes from
`output/combination_result.json`, which is written in the same run.
"""

from __future__ import annotations

from datetime import date
from pathlib import Path

PREDICTION_NOTE = (
    "the two channels normalise to slightly different aMC@NLO references for the same quantity "
    "(1953.9 pb for mu mu, 1944.9 pb for tau tau, a 0.47 % difference discussed in "
    "[docs/01-inputs.md](docs/01-inputs.md)), which is why the combination is done on the cross "
    "sections and not on `mu_Z`"
)

REFERENCES = [
    ("CMS, 13 TeV, 206 pb^-1, 60 < m < 120 GeV", "1952 +- 4 (stat) +- 18 (syst) +- 45 (lumi) pb",
     "[CMS-SMP-20-004, arXiv:2408.03744](https://arxiv.org/abs/2408.03744)"),
    ("ATLAS, 13 TeV, 81 pb^-1, 66 < m < 116 GeV", "1981 +- 7 (stat) +- 38 (syst) +- 42 (lumi) pb",
     "[arXiv:1603.09222](https://arxiv.org/abs/1603.09222)"),
]


def _table(headers, rows, align=None) -> str:
    align = align or ["---"] * len(headers)
    out = ["| " + " | ".join(headers) + " |", "|" + "|".join(align) + "|"]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


def render(p: dict) -> str:
    c = p["combined"]
    mm, tt = p["channels"]["mumu"], p["channels"]["tautau"]
    lik, rat = p["likelihood"], p["ratio"]
    v = p["variations"]
    rel = 100 * c["relative"]

    channel_rows = []
    for ch, name in ((mm, "Z -> mu mu"), (tt, "Z -> tau_h tau_h")):
        gof = f"{ch['gof_p']:.2f}" if ch["gof_p"] is not None else "n/a"
        channel_rows.append([f"**{name}**", ch["variant"],
                             f"{ch['mu']:.4f} +{ch['mu_err_up']:.4f} -{ch['mu_err_down']:.4f}",
                             f"{ch['sigma_pred_pb']:.1f}",
                             f"**{ch['sigma_pb']:.0f} +- {ch['sigma_err_pb']:.0f}**",
                             f"{100 * ch['sigma_err_pb'] / ch['sigma_pb']:.1f} %", gof])

    breakdown_rows = [[k, f"{val:.2f}", f"{100 * val / c['sigma_pb']:.2f} %",
                       "yes" if next(s["rho"] for s in p["sources"] if s["name"] == k) >= 0.999 else "no"]
                      for k, val in c["breakdown_pb"].items() if val >= 0.05]

    var_rows = [[k.replace("_", " "), f"{d['value']:.1f}", f"{d['shift']:+.1f}",
                 f"{d['shift'] / c['total_pb']:+.2f}", d["why"]]
                for k, d in v.items() if k != "baseline"]

    source_rows = [[s["name"], "1" if s["rho"] >= 0.999 else ("0" if s["rho"] <= 0.001 else f"{s['rho']:.2f}"),
                    f"{s['sizes_pb'].get('mumu', 0):.2f}", f"{s['sizes_pb'].get('tautau', 0):.2f}"]
                   for s in sorted(p["sources"], key=lambda s: -max(s["sizes_pb"].values()))]

    return f"""# Combined Z cross section from Z -> mu mu and Z -> tau_h tau_h

*Generated by `run_combination.py` on {date.today().isoformat()} from
`output/combination_result.json`. Do not edit by hand -- edit the code or the docs.*

CMS Open Data 2016, Run2016G+H, L = 16393.381 pb^-1 (normtag), sqrt(s) = 13 TeV.

## Result

> **sigma(pp -> Z/gamma* -> ll, 60 < m_ll < 120 GeV) = {c['sigma_pb']:.0f} +- {c['total_pb']:.0f} pb**
> = {c['sigma_pb']:.0f} +- {c['stat_pb']:.1f} (stat) +- {c['syst_pb']:.0f} (syst)
> +- {c['acc_pb']:.0f} (acc) +- {c['lumi_pb']:.0f} (lumi) pb   ({rel:.2f} %)
>
> per lepton flavour, assuming lepton universality. Channel compatibility:
> chi2/ndf = {c['chi2']:.2f}/{c['ndf']}, p = {c['pvalue']:.2f}.

The profile-likelihood form of the same combination, which carries the tau tau channel's asymmetric uncertainty exactly, gives {lik['value_pb']:.0f} +{lik['err_up_pb']:.0f} / -{lik['err_down_pb']:.0f} pb -- the same answer.

![combined result](output/plots/forest.png)

## Inputs

{_table(["channel", "variant", "mu_Z", "reference [pb]", "sigma(60-120) [pb]", "rel.", "GoF p"],
        channel_rows, ["---", "---", "---", "---:", "---:", "---:", "---:"])}

Both are TRExFitter v1.8.0 profile-likelihood fits performed by the channel groups; this
combination reads their published results (`{mm['provenance'][0]}`,
`{tt['provenance'][0]}`) and does not refit. The `reference` column is the aMC@NLO prediction each
channel's `mu_Z` multiplies -- {PREDICTION_NOTE}. The `mu_Z` uncertainty shown is the in-fit one; the acceptance uncertainty (0.61 % for mu mu, 3.7 % for tau tau) sits outside both fits and is added in the `sigma` column.

The z-mumu input is the **counting extraction** recommended by that channel's review
(`z-mumu/REVIEW.md`, finding F3: the 30-bin shape fit moves `mu_Z` by up to 1.5 % with the binning
and the shape systematics, so the review asks for the counting value plus a +-0.7 % lineshape
term until the `SigModel` template is fixed). Using the 30-bin fit instead shifts the combination
by {v['mumu_shapefit']['shift']:+.1f} pb, listed under the variations below.

## Where the uncertainty comes from

{_table(["source", "pb", "of sigma", "correlated?"], breakdown_rows, ["---", "---:", "---:", ":---:"])}

![uncertainty breakdown](output/plots/breakdown.png)

The combination is **luminosity-dominated and completely dominated by the mu mu channel**:

* weights: mu mu {c['weights']['mumu']:+.4f}, tau tau {c['weights']['tautau']:+.4f};
* mu mu alone gives {mm['alone_pb']:.0f} +- {mm['alone_err_pb']:.0f} pb, so adding the tau tau channel improves the uncertainty by {100 * (1 - c['total_pb'] / mm['alone_err_pb']):.2f} % -- it changes nothing;
* the tau tau weight is **negative**. That is standard BLUE behaviour, not an error: when the correlation exceeds the ratio of the two uncertainties ({c['correlation_mumu_tautau']:.2f} > {mm['alone_err_pb'] / tt['alone_err_pb']:.2f} here), the less precise measurement is used to pull on the shared systematic rather than to average the value down. Its effect is {abs(c['sigma_pb'] - mm['alone_pb']):.1f} pb.

The reason there is nothing to gain: the luminosity uncertainty is {c['lumi_pb']:.0f} pb, fully correlated between the channels and therefore irreducible by combining. Both channels use the same 16393.381 pb^-1 with the same 1.2 %. A third channel of comparable precision would not help either; a better luminosity calibration would.

## Lepton universality

This is the part the combination cannot test, because it *assumes* universality. Measured
separately, with everything correlated cancelling:

> **R = sigma(Z -> tau tau) / sigma(Z -> mu mu) = {rat['value']:.2f} +- {rat['error']:.2f}**
> ({rat['z']:+.1f} sigma from 1, p = {rat['pvalue']:.2f})

![lepton universality](output/plots/universality.png)

## Cross-checks and variations

{_table(["variation", "sigma [pb]", "shift", "in sigma", "what it changes"], var_rows,
        ["---", "---:", "---:", "---:", "---"])}

Every variation moves the result by less than {max(abs(d['shift']) for k, d in v.items() if k != 'baseline') / c['total_pb']:.2f} of the total uncertainty, and the two rows that bracket the correlation model (`rho zero`, `rho one`) span only {abs(v['rho_zero']['value'] - v['rho_one']['value']):.1f} pb. The correlation model is therefore not the limiting assumption -- the luminosity calibration is.

![variations](output/plots/variations.png)

## Comparison with published measurements

{_table(["measurement", "value", "reference"], [[a, b, c_] for a, b, c_ in REFERENCES])}

This work: **{c['sigma_pb']:.0f} +- {c['total_pb']:.0f} pb** (60 < m < 120 GeV). It agrees with the CMS measurement of the same quantity within {abs(c['sigma_pb'] - 1952) / (c['total_pb'] ** 2 + 49 ** 2) ** 0.5:.1f} sigma, and with the aMC@NLO reference the channels normalise to (1945-1954 pb) within {abs(c['sigma_pb'] - 1949) / c['total_pb']:.1f} sigma. The ATLAS number is quoted in a narrower mass window (66-116 GeV) and is not directly comparable.

![comparison](output/plots/comparison.png)

## Correlation model in full

{_table(["source", "rho", "mu mu [pb]", "tau tau [pb]"], source_rows, ["---", ":---:", "---:", "---:"])}

Justification for every row: [docs/02-correlation-model.md](docs/02-correlation-model.md).

## What this is not

This is a **covariance combination of two TRExFitter fits, not a TRExFitter MultiFit.** The
channel workspaces are not committed to the repository and were not rebuilt, so the shared
nuisance parameters are correlated through their `Category` labels instead of being profiled
jointly. The MultiFit configuration is generated and syntax-checked
([fit/comb.config](fit/comb.config), [fit/run_multifit.py](fit/run_multifit.py)) and the exact
recipe to run it is in that file; [docs/03-method.md](docs/03-method.md) explains what the joint
fit would add. At this precision the difference is expected to be small -- the mu mu channel
dominates and its own fit is already profiled -- but it is not zero, and the claim is not made.

Known caveats inherited from the inputs, none of them corrected here:

* `z-mumu/REVIEW.md` F8: `MuonReco` is documented as 0.4 % per muon but applied as 0.4 % per
  event. If the per-muon reading is right, the mu mu muon-efficiency term grows by 0.35 % in
  quadrature (+3 pb on the combined uncertainty, no shift in the value).
* `z-mumu/REVIEW.md` F6: the pileup profile is ~4 % low; the channel quotes 0.16 % for it.
* `z-tautau` open issue 1: the nominal fake factor double-counts genuine taus; the `mcsub`
  variant is listed above and shifts the combination by
  {v['tautau_mcsub']['shift']:+.1f} pb.

## Reproduce

```bash
source ../setup.sh
python run_combination.py          # checks, result, figures, JSON, this file
python run_combination.py --check  # input validation and closure tests only
```
"""


def write_result_md(payload: dict, path: Path) -> Path:
    path.write_text(render(payload))
    return path
